# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchTab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchTab
    pod 'SnapKit'
  target 'SearchTabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchTabUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
